name: Build Github release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy releases into pub stageing folder
        run: |
          Get-ChildItem ./releases -File | Copy-Item -Destination ./pub
          Get-ChildItem ./patches.json -File | Copy-Item -Destination ./pub
          Get-ChildItem ./patches.json -File | Copy-Item -Destination ./releases/patches.json

          New-Item -ItemType Directory -Force -Path ./pub/GOG
          New-Item -ItemType Directory -Force -Path ./pub/v1.1
          New-Item -ItemType Directory -Force -Path ./pub/v1.1_bxit

      - name: Apply v1.3 to GOG
        run: |
          ./releases/CyberstormPatcher.exe ./originals/GOG

          Get-ChildItem ./originals/GOG -File | 
            Copy-Item -Destination ./pub/GOG -Force

      - name: Apply v1.3 to v1.1
        run: |
          ./releases/CyberstormPatcher.exe ./originals/v1.1

      - name: Apply v1.3 to v1.1_bxit
        run: |
          ./releases/CyberstormPatcher.exe ./originals/v1.1_bxit

      - name: Collect the files
        run: |
          Get-ChildItem ./originals/GOG -File | 
            Copy-Item -Destination ./pub/GOG -Force

          Get-ChildItem ./originals/v1.1 -File | 
            Copy-Item -Destination ./pub/v1.1 -Force

          Get-ChildItem ./originals/v1.1_bxit -File | 
            Copy-Item -Destination ./pub/v1.1_bxit -Force

      - name: Zip release
        run: |
          Compress-Archive `
            -Path ./pub `
            -DestinationPath ./pub/Cyberstorm-V1.3.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.30A
          files: ./pub/Cyberstorm-V1.3.zip
          generate_release_notes: true