name: Build GitHub Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare release folders
        shell: pwsh
        run: |
          Copy-Item ./releases/* ./pub/ -Force
          Copy-Item ./patches.json ./pub/ -Force
          Copy-Item ./patches.json ./releases/ -Force

          New-Item ./pub/GOG -ItemType Directory -Force
          New-Item ./pub/v1.1 -ItemType Directory -Force
          New-Item ./pub/v1.1_bxit -ItemType Directory -Force

      - name: Apply patch
        shell: pwsh
        run: |
          ./releases/CyberstormPatcher.exe ./originals/GOG
          ./releases/CyberstormPatcher.exe ./originals/v1.1
          ./releases/CyberstormPatcher.exe ./originals/v1.1_bxit

      - name: Collect patched files
        shell: pwsh
        run: |
          Copy-Item ./originals/GOG/* ./pub/GOG/ -Force
          Copy-Item ./originals/v1.1/* ./pub/v1.1/ -Force
          Copy-Item ./originals/v1.1_bxit/* ./pub/v1.1_bxit/ -Force

      - name: Create ZIP
        shell: pwsh
        run: |
          Compress-Archive -Path ./pub/* -DestinationPath ./Cyberstorm-V1.3.zip -Force

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.30A
          files: ./Cyberstorm-V1.3.zip
          generate_release_notes: true
