name: Build GitHub Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare release
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path ./pub
          New-Item -ItemType Directory -Force -Path ./pub/GOG
          New-Item -ItemType Directory -Force -Path ./pub/v1.1
          New-Item -ItemType Directory -Force -Path ./pub/v1.1_bxit

          Copy-Item ./releases/* ./pub/ -Force
          Copy-Item ./patches.json ./pub/ -Force
          Copy-Item ./patches.json ./releases/ -Force

      - name: Apply patches
        shell: pwsh
        run: |
          ./releases/CyberstormPatcher.exe ./originals/GOG
          ./releases/CyberstormPatcher.exe ./originals/v1.1
          ./releases/CyberstormPatcher.exe ./originals/v1.1_bxit

      - name: Collect files
        shell: pwsh
        run: |
          Copy-Item ./originals/GOG/* ./pub/GOG/ -Force
          Copy-Item ./originals/v1.1/* ./pub/v1.1/ -Force
          Copy-Item ./originals/v1.1_bxit/* ./pub/v1.1_bxit/ -Force

      - name: Puge originals
        shell: pwsh
        run: |
          Remove-Item ./pub/GOG/original -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item ./pub/v1.1/original -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item ./pub/v1.1_bxit/original -Recurse -Force -ErrorAction SilentlyContinue

      - name: Create ZIP
        shell: pwsh
        run: |
          Compress-Archive `
            -Path ./pub/* `
            -DestinationPath ./Cyberstorm-V1.3.zip `
            -Force

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.30A
          files: ./Cyberstorm-V1.3.zip
          generate_release_notes: true
